import type { Metadata } from "next";
import { DM_Sans, Exo_2} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";



const exo2 = Exo_2({
  variable: "--font-exo2",
  subsets: ['latin']
})

const dmSans = DM_Sans({
  variable: "--font-dm_sans",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      data-theme = 'dark'
      lang="en"
      className={`${exo2.variable} ${dmSans.variable} h-full antialiased`}
    >
      <body className="flex flex-col">
        <Navbar/>
        {children}
        
        </body>
    </html>
  );
}
